AWSTemplateFormatVersion: "2010-09-09"
Description: lambda-docker-serverless

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambda-docker-serverless-deployment
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lambda-docker-serverless-repos
